# Generated by Django 3.2.8 on 2021-10-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户配置中心', 'verbose_name_plural': '用户配置中心'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('secrecy', '保密'), ('male', '男'), ('female', '女')], default='secrecy', max_length=8),
        ),
    ]
