# Generated by Django 3.2.8 on 2021-10-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailverifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=254, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('forget', '找回密码'), ('register', '注册')], default='register', max_length=16, verbose_name='验证种类'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('secrecy', '保密'), ('male', '男'), ('female', '女')], default='secrecy', max_length=8, verbose_name='性别'),
        ),
    ]
