# Generated by Django 3.2.8 on 2021-10-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], default='register', max_length=16, verbose_name='验证种类'),
        ),
    ]
