# Generated by Django 3.2.8 on 2021-10-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_emailverifycode_send_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('forget', '找回密码'), ('register', '注册')], default='register', max_length=16, verbose_name='验证种类'),
        ),
    ]
