# Generated by Django 3.2.10 on 2021-12-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_emailverifycode_send_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], default='register', max_length=16, verbose_name='验证种类'),
        ),
    ]
