# Generated by Django 3.2.8 on 2021-10-22 15:06

import ckeditor5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor5.fields.RichTextField(verbose_name='文章详情 '),
        ),
    ]
