# Generated by Django 3.2.8 on 2021-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('words', models.CharField(max_length=512, verbose_name='在线留言')),
                ('bug', models.CharField(max_length=512, verbose_name='bug提交')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
