# Generated by Django 3.2.8 on 2021-10-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('name', models.CharField(max_length=16, verbose_name='用户姓名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('bug', models.CharField(max_length=512, verbose_name='BUG提交')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='helpsubmit',
            name='bug',
        ),
    ]
