# Generated by Django 3.2.8 on 2021-10-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_auto_20211022_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugsubmit',
            options={'verbose_name': 'bug汇总', 'verbose_name_plural': 'bug汇总'},
        ),
        migrations.AlterField(
            model_name='bugsubmit',
            name='bug',
            field=models.TextField(verbose_name='BUG提交'),
        ),
    ]
