# Generated by Django 3.2.8 on 2021-10-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_auto_20211022_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpsubmit',
            options={'verbose_name': '留言板', 'verbose_name_plural': '留言板'},
        ),
    ]
